In [1]:
import numpy as np 
a = np.random.randn(5)
print(a)

[-0.12818301  0.04417561 -0.2917055  -0.47745213  0.22533749]


In [2]:
print(np.dot(a,a.T))

0.3822119900738125


In [3]:
a = np.random.randn(5,1)
print(a)

[[ 0.37004569]
 [-1.39534323]
 [-0.09795645]
 [-0.71252582]
 [ 0.37252437]]


In [4]:
print(a.T)

[[ 0.37004569 -1.39534323 -0.09795645 -0.71252582  0.37252437]]


In [5]:
print(np.dot(a,a.T))

[[ 0.13693381 -0.51634075 -0.03624836 -0.26366711  0.13785104]
 [-0.51634075  1.94698274  0.13668287  0.99421808 -0.51979936]
 [-0.03624836  0.13668287  0.00959547  0.0697965  -0.03649116]
 [-0.26366711  0.99421808  0.0697965   0.50769304 -0.26543323]
 [ 0.13785104 -0.51979936 -0.03649116 -0.26543323  0.13877441]]
