In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [3]:
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [4]:
print("dtype", x3.dtype)

dtype int32


In [5]:
print("itemssize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemssize: 4 bytes
nbytes: 240 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[4]

7

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[2,0]

1

In [13]:
x2[2,-1]

7

In [14]:
x2[0,0] = 13

In [15]:
x2

array([[13,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
x1[0] = 3.14155 # changed to int

In [17]:
x1

array([3, 0, 3, 3, 7, 9])

In [18]:
x = np.arange(10)

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [24]:
x[1::2] #every other element starting at 1

array([1, 3, 5, 7, 9])

In [25]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x[5::-2] # all elements reversed, every other from index 5

array([5, 3, 1])

### Multidimensional subarrays

In [27]:
x2

array([[13,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x2[:2,:3] #two rows,tree columns

array([[13,  5,  2],
       [ 7,  6,  8]])

In [29]:
x2[:3,:2] #tree rows, two columns

array([[13,  5],
       [ 7,  6],
       [ 1,  6]])

In [30]:
x2[::-1,::-1] 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 13]])

In [31]:
print(x2[:,0]) # first column of x2

[13  7  1]


In [32]:
print(x2[0,:]) # first row of x2

[13  5  2  4]


In [33]:
print(x2[0]) # equivalent to x2[0, :]

[13  5  2  4]


### Subarrays as no-copy views

In [34]:
print(x2)

[[13  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[13  5]
 [ 7  6]]


In [36]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [38]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [39]:
x2_sub_copy[0,0] = 42

In [40]:
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [41]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [42]:
grid = np.arange(1,10).reshape((3,3))

In [43]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1,2,3])

In [45]:
x.reshape((1,3))

array([[1, 2, 3]])

In [46]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [47]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [48]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

## Concatenation of arrays

In [49]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [50]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [51]:
z = [99,99,99]

In [52]:
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [53]:
grid = np.array([[1,2,3],[4,5,6]])

In [54]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [57]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [58]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [59]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [61]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

## The Slowness of Loops

In [62]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [63]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

2.83 s ± 259 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducing UFuncs

In [64]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [65]:
%timeit (1.0 / big_array)

10.7 ms ± 155 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [66]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [67]:
x = np.arange(9).reshape((3,3))

In [68]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [69]:
x = np.arange(4)

In [70]:
print("x =  ",x)
print("x + 5",x + 5)
print("x - 5 ",x - 5)
print("x * 2",x * 2)
print("x / 2",x / 2)
print("x // 2",x // 2)

x =   [0 1 2 3]
x + 5 [5 6 7 8]
x - 5  [-5 -4 -3 -2]
x * 2 [0 2 4 6]
x / 2 [0.  0.5 1.  1.5]
x // 2 [0 0 1 1]


In [71]:
print("-x  ",-x)
print("x ** 2",x ** 2)
print("x %  2 ",x % 2)

-x   [ 0 -1 -2 -3]
x ** 2 [0 1 4 9]
x %  2  [0 1 0 1]


In [72]:
-(0.5 * x + 1) -2 

array([-3. , -3.5, -4. , -4.5])

In [73]:
np.add(x,2)

array([2, 3, 4, 5])

### Absolute value

In [74]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [75]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [76]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [77]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions

In [78]:
theta = np.linspace(0, np.pi, 3)

In [79]:
print("theta   = ", theta)
print("sin(theta) = ",np.sin(theta))
print("cos(theta) = ",np.cos(theta))
print("tan(theta) = ",np.tan(theta))

theta   =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [81]:
x = [-1, 0, 1]

In [82]:
print("x   = ", x)
print("arcsin(x) = ",np.arcsin(x))
print("arccos(x) = ",np.arccos(x))
print("arctan(x) = ",np.arctan(x))

x   =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [85]:
x = [1,2,3]
print("x   = ",x)
print("e^x = ",np.exp(x))
print("2^x = ",np.exp2(x))
print("3^x = ",np.power(3,x))

x   =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [86]:
x =[1,2,4,10]
print("x        = ",x)
print("ln(x)    = ",np.log(x))
print("log2(x)  = ",np.log2(x))
print("log10(x) = ",np.log10(x))

x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [87]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =",np.expm1(x))
print("log(1 + x) =",np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


### Specialized ufuncs

In [88]:
from scipy import special

In [89]:
x = [1, 5, 10]
print("gamma(x)    = ", special.gamma(x))
print("ln|gamma(x) = ", special.gammaln(x))
print("beta(x, 2)  = ", special.beta(x, 2))

gamma(x)    =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x) =  [ 0.          3.17805383 12.80182748]
beta(x, 2)  =  [0.5        0.03333333 0.00909091]


In [91]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)    =",special.erf(x))
print("erfc(x)   =",special.erfc(x))
print("erfinv(x) =",special.erfinv(x))

erf(x)    = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]
