In [2]:
import numpy as np
np.random.seed(0)

In [5]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [6]:
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [7]:
print("dtype", x3.dtype)

dtype int32


In [9]:
print("itemssize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemssize: 4 bytes
nbytes: 240 bytes


In [10]:
x1

array([3, 5, 2, 4, 7, 6])

In [11]:
x1[0]

3

In [15]:
x1[4]

7

In [14]:
x1[-1]

6

In [16]:
x1[-2]

7

In [17]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [18]:
x2[2,0]

5

In [19]:
x2[2,-1]

9

In [20]:
x2[0,0] = 13

In [21]:
x2

array([[13,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [24]:
x1[0] = 3.14155 # changed to int

In [25]:
x1

array([3, 5, 2, 4, 7, 6])

In [26]:
x = np.arange(10)

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[5:]

array([5, 6, 7, 8, 9])

In [30]:
x[4:7]

array([4, 5, 6])

In [32]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [34]:
x[1::2] #every other element starting at 1

array([1, 3, 5, 7, 9])

In [35]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5::-2] # all elements reversed, every other from index 5

array([5, 3, 1])

### Multidimensional subarrays

In [39]:
x2

array([[13,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

In [44]:
x2[:2,:3] #two rows,tree columns

array([[13,  8,  1],
       [ 7,  7,  8]])

In [45]:
x2[:3,:2] #tree rows, two columns

array([[13,  8],
       [ 7,  7],
       [ 5,  9]])

In [43]:
x2[::-1,::-1] 

array([[ 9,  8,  9,  5],
       [ 1,  8,  7,  7],
       [ 6,  1,  8, 13]])

In [47]:
print(x2[:,0]) # first column of x2

[13  7  5]


In [50]:
print(x2[0,:]) # first row of x2

[13  8  1  6]


In [51]:
print(x2[0]) # equivalent to x2[0, :]

[13  8  1  6]


### Subarrays as no-copy views

In [52]:
print(x2)

[[13  8  1  6]
 [ 7  7  8  1]
 [ 5  9  8  9]]


In [54]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[13  8]
 [ 7  7]]


In [55]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  8]
 [ 7  7]]


In [56]:
print(x2)

[[99  8  1  6]
 [ 7  7  8  1]
 [ 5  9  8  9]]


### Creating copies of arrays

In [57]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  8]
 [ 7  7]]


In [58]:
x2_sub_copy[0,0] = 42

In [59]:
print(x2_sub_copy)

[[42  8]
 [ 7  7]]


In [60]:
print(x2)

[[99  8  1  6]
 [ 7  7  8  1]
 [ 5  9  8  9]]


### Reshaping of Arrays

In [61]:
grid = np.arange(1,10).reshape((3,3))

In [62]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
x = np.array([1,2,3])

In [64]:
x.reshape((1,3))

array([[1, 2, 3]])

In [65]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [66]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [67]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])