In [1]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [3]:
print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [4]:
print("dtype", x3.dtype)

dtype int32


In [5]:
print("itemssize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemssize: 4 bytes
nbytes: 240 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0]

5

In [8]:
x1[4]

7

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[2,0]

1

In [13]:
x2[2,-1]

7

In [14]:
x2[0,0] = 13

In [15]:
x2

array([[13,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [16]:
x1[0] = 3.14155 # changed to int

In [17]:
x1

array([3, 0, 3, 3, 7, 9])

In [18]:
x = np.arange(10)

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[:5]

array([0, 1, 2, 3, 4])

In [21]:
x[5:]

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [23]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [24]:
x[1::2] #every other element starting at 1

array([1, 3, 5, 7, 9])

In [25]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x[5::-2] # all elements reversed, every other from index 5

array([5, 3, 1])

### Multidimensional subarrays

In [27]:
x2

array([[13,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x2[:2,:3] #two rows,tree columns

array([[13,  5,  2],
       [ 7,  6,  8]])

In [29]:
x2[:3,:2] #tree rows, two columns

array([[13,  5],
       [ 7,  6],
       [ 1,  6]])

In [30]:
x2[::-1,::-1] 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 13]])

In [31]:
print(x2[:,0]) # first column of x2

[13  7  1]


In [32]:
print(x2[0,:]) # first row of x2

[13  5  2  4]


In [33]:
print(x2[0]) # equivalent to x2[0, :]

[13  5  2  4]


### Subarrays as no-copy views

In [34]:
print(x2)

[[13  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[13  5]
 [ 7  6]]


In [36]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [38]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [39]:
x2_sub_copy[0,0] = 42

In [40]:
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [41]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

In [42]:
grid = np.arange(1,10).reshape((3,3))

In [43]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
x = np.array([1,2,3])

In [45]:
x.reshape((1,3))

array([[1, 2, 3]])

In [46]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [47]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [48]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

## Concatenation of arrays

In [49]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [57]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [58]:
z = [99,99,99]

In [59]:
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [61]:
grid = np.array([[1,2,3],[4,5,6]])

In [62]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [65]:
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [66]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [67]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [69]:
left, right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Computation on NumPy Arrays: Universal Functions

## The Slowness of Loops

In [70]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [71]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

3.36 s ± 328 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Introducing UFuncs

In [72]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [74]:
%timeit (1.0 / big_array)

13.3 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [75]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [76]:
x = np.arange(9).reshape((3,3))

In [77]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [78]:
x = np.arange(4)

In [81]:
print("x =  ",x)
print("x + 5",x + 5)
print("x - 5 ",x - 5)
print("x * 2",x * 2)
print("x / 2",x / 2)
print("x // 2",x // 2)

x =   [0 1 2 3]
x + 5 [5 6 7 8]
x - 5  [-5 -4 -3 -2]
x * 2 [0 2 4 6]
x / 2 [0.  0.5 1.  1.5]
x // 2 [0 0 1 1]


In [82]:
print("-x  ",-x)
print("x ** 2",x ** 2)
print("x %  2 ",x % 2)

-x   [ 0 -1 -2 -3]
x ** 2 [0 1 4 9]
x %  2  [0 1 0 1]


In [84]:
-(0.5 * x + 1) -2 

array([-3. , -3.5, -4. , -4.5])

In [85]:
np.add(x,2)

array([2, 3, 4, 5])

### Absolute value